In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/lending raw/loan/accepted_2007_to_2018Q4.csv", low_memory=False)

In [3]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(2260701, 151)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Columns: 151 entries, id to settlement_term
dtypes: float64(113), object(38)
memory usage: 2.5+ GB

In [6]:
df.describe()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
count,0.0,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260668e+06,2.260664e+06,2.258957e+06,2.260639e+06,2.260668e+06,...,10917.0,10917.000000,10917.0,10917.000000,8651.000000,10917.000000,10917.000000,34246.000000,34246.000000,34246.000000
mean,NaN,1.504693e+04,1.504166e+04,1.502344e+04,1.309283e+01,4.458068e+02,7.799243e+04,1.882420e+01,3.068792e-01,6.985882e+02,...,3.0,155.045981,3.0,13.743886,454.798089,11636.883942,193.994321,5010.664267,47.780365,13.191322
std,NaN,9.190245e+03,9.188413e+03,9.192332e+03,4.832138e+00,2.671735e+02,1.126962e+05,1.418333e+01,8.672303e-01,3.301038e+01,...,0.0,129.040594,0.0,9.671178,375.385500,7625.988281,198.629496,3693.122590,7.311822,8.159980
min,NaN,5.000000e+02,5.000000e+02,0.000000e+00,5.310000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,6.100000e+02,...,3.0,0.640000,3.0,0.000000,1.920000,55.730000,0.010000,44.210000,0.200000,0.000000
25%,NaN,8.000000e+03,8.000000e+03,8.000000e+03,9.490000e+00,2.516500e+02,4.600000e+04,1.189000e+01,0.000000e+00,6.750000e+02,...,3.0,59.440000,3.0,5.000000,175.230000,5627.000000,44.440000,2208.000000,45.000000,6.000000
50%,NaN,1.290000e+04,1.287500e+04,1.280000e+04,1.262000e+01,3.779900e+02,6.500000e+04,1.784000e+01,0.000000e+00,6.900000e+02,...,3.0,119.140000,3.0,15.000000,352.770000,10028.390000,133.160000,4146.110000,45.000000,14.000000
75%,NaN,2.000000e+04,2.000000e+04,2.000000e+04,1.599000e+01,5.933200e+02,9.300000e+04,2.449000e+01,0.000000e+00,7.150000e+02,...,3.0,213.260000,3.0,22.000000,620.175000,16151.890000,284.190000,6850.172500,50.000000,18.000000
max,NaN,4.000000e+04,4.000000e+04,4.000000e+04,3.099000e+01,1.719830e+03,1.100000e+08,9.990000e+02,5.800000e+01,8.450000e+02,...,3.0,943.940000,3.0,37.000000,2680.890000,40306.410000,1407.860000,33601.000000,521.350000,181.000000

In [7]:
df.describe(include='object')

,id,term,grade,sub_grade,emp_title,emp_length,home_ownership,verification_status,issue_d,loan_status,...,hardship_status,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_loan_status,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date
count,2260701,2260668,2260668,2260668,2093699,2113761,2260668,2260668,2260668,2260668,...,10917,10917,10917,10917,10917,2260668,2260668,34246,34246,34246
unique,2260701,2,7,35,512694,11,6,3,139,9,...,3,27,28,27,5,2,2,83,3,90
top,68407277,36 months,B,C1,Teacher,10+ years,MORTGAGE,Source Verified,Mar-2016,Fully Paid,...,COMPLETED,Sep-2017,Dec-2017,Sep-2017,Late (16-30 days),Cash,N,Feb-2019,ACTIVE,Jan-2019
freq,1,1609754,663557,145903,38824,748005,1111450,886231,61992,1076751,...,7819,2444,1756,1715,4770,2182546,2226422,2606,14704,1710

In [8]:
df.columns.to_list()

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'sub_grade',
 'emp_title',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'url',
 'desc',
 'purpose',
 'title',
 'zip_code',
 'addr_state',
 'dti',
 'delinq_2yrs',
 'earliest_cr_line',
 'fico_range_low',
 'fico_range_high',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'revol_util',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'last_fico_range_high',
 'last_fico_range_low',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_act_il',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'total_rev_hi_lim',
 'inq_fi',
 'total_cu_tl',
 'inq_last_12m',
 'acc_open_past_24mths',
 'avg_cur_bal',
 'bc_open_to_buy',
 'bc_util',
 'chargeoff_within_12_mths',
 'delinq_amnt',
 'mo_sin_old_il_acct',
 'mo_sin_old_rev_tl_op',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mort_acc',
 'mths_since_recent_bc',
 'mths_since_recent_bc_dlq',
 'mths_since_recent_inq',
 'mths_since_recent_revol_delinq',
 'num_accts_ever_120_pd',
 'num_actv_bc_tl',
 'num_actv_rev_tl',
 'num_bc_sats',
 'num_bc_tl',
 'num_il_tl',
 'num_op_rev_tl',
 'num_rev_accts',
 'num_rev_tl_bal_gt_0',
 'num_sats',
 'num_tl_120dpd_2m',
 'num_tl_30dpd',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'percent_bc_gt_75',
 'pub_rec_bankruptcies',
 'tax_liens',
 'tot_hi_cred_lim',
 'total_bal_ex_mort',
 'total_bc_limit',
 'total_il_high_credit_limit',
 'revol_bal_joint',
 'sec_app_fico_range_low',
 'sec_app_fico_range_high',
 'sec_app_earliest_cr_line',
 'sec_app_inq_last_6mths',
 'sec_app_mort_acc',
 'sec_app_open_acc',
 'sec_app_revol_util',
 'sec_app_open_act_il',
 'sec_app_num_rev_accts',
 'sec_app_chargeoff_within_12_mths',
 'sec_app_collections_12_mths_ex_med',
 'sec_app_mths_since_last_major_derog',
 'hardship_flag',
 'hardship_type',
 'hardship_reason',
 'hardship_status',
 'deferral_term',
 'hardship_amount',
 'hardship_start_date',
 'hardship_end_date',
 'payment_plan_start_date',
 'hardship_length',
 'hardship_dpd',
 'hardship_loan_status',
 'orig_projected_additional_accrued_interest',
 'hardship_payoff_balance_amount',
 'hardship_last_payment_amount',
 'disbursement_method',
 'debt_settlement_flag',
 'debt_settlement_flag_date',
 'settlement_status',
 'settlement_date',
 'settlement_amount',
 'settlement_percentage',
 'settlement_term']

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
numerical_df = df.select_dtypes(include=[np.number])
numerical_df.head()

,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,...,deferral_term,hardship_amount,hardship_length,hardship_dpd,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,settlement_amount,settlement_percentage,settlement_term
0,NaN,3600.0,3600.0,3600.0,13.99,123.03,55000.0,5.91,0.0,675.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,24700.0,24700.0,24700.0,11.99,820.28,65000.0,16.06,1.0,715.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,20000.0,20000.0,20000.0,10.78,432.66,63000.0,10.78,0.0,695.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,35000.0,35000.0,35000.0,14.85,829.90,110000.0,17.06,0.0,785.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,10400.0,10400.0,10400.0,22.45,289.91,104433.0,25.37,1.0,695.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
categorical_df = df.select_dtypes(exclude=[np.number])
categorical_df.head()

,id,term,grade,sub_grade,emp_title,emp_length,home_ownership,verification_status,issue_d,loan_status,...,hardship_status,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_loan_status,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date
0,68407277,36 months,C,C4,leadman,10+ years,MORTGAGE,Not Verified,Dec-2015,Fully Paid,...,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN
1,68355089,36 months,C,C1,Engineer,10+ years,MORTGAGE,Not Verified,Dec-2015,Fully Paid,...,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN
2,68341763,60 months,B,B4,truck driver,10+ years,MORTGAGE,Not Verified,Dec-2015,Fully Paid,...,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN
3,66310712,60 months,C,C5,Information Systems Officer,10+ years,MORTGAGE,Source Verified,Dec-2015,Current,...,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN
4,68476807,60 months,F,F1,Contract Specialist,3 years,MORTGAGE,Source Verified,Dec-2015,Fully Paid,...,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN

In [12]:
summary = pd.DataFrame({
        "Column": df.columns, 
        "Data Type": df.dtypes.values, 
        "Missing Values": df.isnull().sum().values, 
        "Missing %": (df.isnull().sum().values / len(df) * 100).round(2), 
        "Unique Values": df.nunique().values})

summary = summary.sort_values('Missing %', ascending=False).reset_index(drop=True)
summary.head(60)

,Column,Data Type,Missing Values,Missing %,Unique Values
0,member_id,float64,2260701,100.00,0
1,orig_projected_additional_accrued_interest,float64,2252050,99.62,7487
2,hardship_reason,object,2249784,99.52,9
3,hardship_payoff_balance_amount,float64,2249784,99.52,10893
4,hardship_last_payment_amount,float64,2249784,99.52,9045
5,payment_plan_start_date,object,2249784,99.52,27
6,hardship_type,object,2249784,99.52,1
7,hardship_status,object,2249784,99.52,3
8,hardship_start_date,object,2249784,99.52,27
9,deferral_term,float64,2249784,99.52,1
10,hardship_amount,float64,2249784,99.52,9162
11,hardship_dpd,float64,2249784,99.52,34
12,hardship_loan_status,object,2249784,99.52,5
13,hardship_length,float64,2249784,99.52,1
14,hardship_end_date,object,2249784,99.52,28
15,settlement_status,object,2226455,98.49,3
16,debt_settlement_flag_date,object,2226455,98.49,83
17,settlement_term,float64,2226455,98.49,40
18,settlement_percentage,float64,2226455,98.49,2070
19,settlement_date,object,2226455,98.49,90
20,settlement_amount,float64,2226455,98.49,21941
21,sec_app_mths_since_last_major_derog,float64,2224759,98.41,140
22,sec_app_revol_util,float64,2154517,95.30,1216
23,sec_app_num_rev_accts,float64,2152680,95.22,86
24,sec_app_earliest_cr_line,object,2152680,95.22,663
25,sec_app_mort_acc,float64,2152680,95.22,23
26,sec_app_open_acc,float64,2152680,95.22,67
27,revol_bal_joint,float64,2152681,95.22,56875
28,sec_app_fico_range_low,float64,2152680,95.22,62
29,sec_app_open_act_il,float64,2152680,95.22,40
30,sec_app_inq_last_6mths,float64,2152680,95.22,7
31,sec_app_fico_range_high,float64,2152680,95.22,62
32,sec_app_collections_12_mths_ex_med,float64,2152680,95.22,18
33,sec_app_chargeoff_within_12_mths,float64,2152680,95.22,22
34,verification_status_joint,object,2144971,94.88,3
35,annual_inc_joint,float64,2139991,94.66,17633
36,dti_joint,float64,2139995,94.66,4018
37,desc,object,2134636,94.42,124500
38,mths_since_last_record,float64,1901545,84.11,129
39,mths_since_recent_bc_dlq,float64,1741000,77.01,177
40,mths_since_last_major_derog,float64,1679926,74.31,183
41,mths_since_recent_revol_delinq,float64,1520342,67.25,179
42,next_pymnt_d,object,1345343,59.51,106
43,mths_since_last_delinq,float64,1158535,51.25,173
44,il_util,float64,1068883,47.28,280
45,mths_since_rcnt_il,float64,909957,40.25,405
46,all_util,float64,866381,38.32,188
47,open_il_24m,float64,866162,38.31,31
48,open_rv_24m,float64,866162,38.31,50
49,max_bal_bc,float64,866162,38.31,33726
50,inq_fi,float64,866162,38.31,33
51,total_cu_tl,float64,866163,38.31,62
52,inq_last_12m,float64,866163,38.31,48
53,open_acc_6m,float64,866163,38.31,19
54,open_act_il,float64,866162,38.31,54
55,open_il_12m,float64,866162,38.31,19
56,open_rv_12m,float64,866162,38.31,29
57,total_bal_il,float64,866162,38.31,162249
58,mths_since_recent_inq,float64,295468,13.07,26
59,emp_title,object,167002,7.39,512694

In [13]:
print(len(summary[summary["Missing %"] == 100]))
print(summary.loc[summary["Missing %"] == 100, "Column"].tolist())

1
['member_id']

In [14]:
print(len(summary[(summary["Missing %"] >= 90) & (summary["Missing %"] < 100)]))
print(summary.loc[(summary["Missing %"] >= 90) & (summary["Missing %"] < 100), "Column"].tolist())

37
['orig_projected_additional_accrued_interest', 'hardship_reason', 'hardship_payoff_balance_amount', 'hardship_last_payment_amount', 'payment_plan_start_date', 'hardship_type', 'hardship_status', 'hardship_start_date', 'deferral_term', 'hardship_amount', 'hardship_dpd', 'hardship_loan_status', 'hardship_length', 'hardship_end_date', 'settlement_status', 'debt_settlement_flag_date', 'settlement_term', 'settlement_percentage', 'settlement_date', 'settlement_amount', 'sec_app_mths_since_last_major_derog', 'sec_app_revol_util', 'sec_app_num_rev_accts', 'sec_app_earliest_cr_line', 'sec_app_mort_acc', 'sec_app_open_acc', 'revol_bal_joint', 'sec_app_fico_range_low', 'sec_app_open_act_il', 'sec_app_inq_last_6mths', 'sec_app_fico_range_high', 'sec_app_collections_12_mths_ex_med', 'sec_app_chargeoff_within_12_mths', 'verification_status_joint', 'annual_inc_joint', 'dti_joint', 'desc']

In [15]:
print(len(summary[(summary["Missing %"] >= 50) & (summary["Missing %"] < 90)]))
print(summary.loc[(summary["Missing %"] >= 50) & (summary["Missing %"] < 90), "Column"].tolist())

6
['mths_since_last_record', 'mths_since_recent_bc_dlq', 'mths_since_last_major_derog', 'mths_since_recent_revol_delinq', 'next_pymnt_d', 'mths_since_last_delinq']

In [16]:
print(len(summary[(summary["Missing %"] >= 20) & (summary["Missing %"] < 50)]))
print(summary.loc[(summary["Missing %"] >= 20) & (summary["Missing %"] < 50), "Column"].tolist())

14
['il_util', 'mths_since_rcnt_il', 'all_util', 'open_il_24m', 'open_rv_24m', 'max_bal_bc', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_rv_12m', 'total_bal_il']

In [17]:
print(len(summary[(summary["Missing %"] > 0) & (summary["Missing %"] < 20)]))
print(summary.loc[(summary["Missing %"] > 0) & (summary["Missing %"] < 20), "Column"].tolist())

44
['mths_since_recent_inq', 'emp_title', 'num_tl_120dpd_2m', 'emp_length', 'mo_sin_old_il_acct', 'bc_util', 'percent_bc_gt_75', 'bc_open_to_buy', 'mths_since_recent_bc', 'pct_tl_nvr_dlq', 'num_tl_30dpd', 'mo_sin_old_rev_tl_op', 'num_bc_tl', 'num_rev_accts', 'num_tl_op_past_12m', 'num_il_tl', 'avg_cur_bal', 'tot_coll_amt', 'total_rev_hi_lim', 'mo_sin_rcnt_rev_tl_op', 'tot_cur_bal', 'num_actv_rev_tl', 'num_actv_bc_tl', 'mo_sin_rcnt_tl', 'num_accts_ever_120_pd', 'num_rev_tl_bal_gt_0', 'num_tl_90g_dpd_24m', 'tot_hi_cred_lim', 'total_il_high_credit_limit', 'num_op_rev_tl', 'num_bc_sats', 'num_sats', 'mort_acc', 'total_bal_ex_mort', 'total_bc_limit', 'acc_open_past_24mths', 'title', 'last_pymnt_d', 'revol_util', 'dti', 'pub_rec_bankruptcies', 'tax_liens', 'collections_12_mths_ex_med', 'chargeoff_within_12_mths']

In [18]:
print(len(summary[summary["Missing %"] == 0]))
print(summary.loc[summary["Missing %"] == 0, "Column"].tolist())

49
['purpose', 'loan_amnt', 'id', 'pymnt_plan', 'url', 'loan_status', 'issue_d', 'annual_inc', 'verification_status', 'installment', 'grade', 'home_ownership', 'sub_grade', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate', 'zip_code', 'acc_now_delinq', 'application_type', 'policy_code', 'delinq_amnt', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'inq_last_6mths', 'fico_range_high', 'pub_rec', 'open_acc', 'out_prncp_inv', 'fico_range_low', 'delinq_2yrs', 'addr_state', 'out_prncp', 'initial_list_status', 'total_acc', 'revol_bal', 'last_credit_pull_d', 'last_pymnt_amnt', 'last_fico_range_low', 'last_fico_range_high', 'collection_recovery_fee', 'recoveries', 'total_rec_late_fee', 'total_rec_int', 'earliest_cr_line', 'hardship_flag', 'disbursement_method', 'debt_settlement_flag']

Drop columns > 90% missing

In [19]:
drop_cols = summary.loc[summary["Missing %"] >= 90, "Column"].tolist()
df = df.drop(columns=drop_cols)

In [20]:
df.shape

(2260701, 113)

In [21]:
df.isnull().sum().sort_values(ascending=False).head(20)

mths_since_last_record            1901545
mths_since_recent_bc_dlq          1741000
mths_since_last_major_derog       1679926
mths_since_recent_revol_delinq    1520342
next_pymnt_d                      1345343
mths_since_last_delinq            1158535
il_util                           1068883
mths_since_rcnt_il                 909957
all_util                           866381
total_cu_tl                        866163
inq_last_12m                       866163
open_acc_6m                        866163
total_bal_il                       866162
max_bal_bc                         866162
open_rv_12m                        866162
inq_fi                             866162
open_il_12m                        866162
open_act_il                        866162
open_rv_24m                        866162
open_il_24m                        866162
dtype: int64

In [22]:
summary = pd.DataFrame({
        "Column": df.columns,
        "Missing Values": df.isnull().sum().values,
        "Missing %": (df.isnull().sum().values / len(df) * 100).round(2)
})

summary = summary.sort_values("Missing %", ascending=False)
summary.head(20)

                            Column  Missing Values  Missing %
29          mths_since_last_record         1901545      84.11
85        mths_since_recent_bc_dlq         1741000      77.01
52     mths_since_last_major_derog         1679926      74.31
87  mths_since_recent_revol_delinq         1520342      67.25
47                    next_pymnt_d         1345343      59.51
28          mths_since_last_delinq         1158535      51.25
64                         il_util         1068883      47.28
62              mths_since_rcnt_il          909957      40.25
68                        all_util          866381      38.32
58                     open_acc_6m          866163      38.31
59                     open_act_il          866162      38.31
66                     open_rv_24m          866162      38.31
65                     open_rv_12m          866162      38.31
70                          inq_fi          866162      38.31
71                     total_cu_tl          866163      38.31
72                    inq_last_12m          866163      38.31
67                      max_bal_bc          866162      38.31
63                    total_bal_il          866162      38.31
60                     open_il_12m          866162      38.31
61                     open_il_24m          866162      38.31

Columns bigger then 50%

In [23]:
cols_50 = summary.loc[summary["Missing %"] >= 50, "Column"].tolist()

print(cols_50)

['mths_since_last_record', 'mths_since_recent_bc_dlq', 'mths_since_last_major_derog', 'mths_since_recent_revol_delinq', 'next_pymnt_d', 'mths_since_last_delinq']

In [24]:
cols_50 = [
    "mths_since_last_record",
    "mths_since_recent_bc_dlq",
    "mths_since_last_major_derog",
    "mths_since_recent_revol_delinq",
    "mths_since_last_delinq",
    "next_pymnt_d"
]

for col in cols_50:
    print("\n", col)
    print(
        df.groupby("loan_status")[col]
          .apply(lambda x: x.isna().mean() * 100)
          .round(2)
    )

 mths_since_last_record
loan_status
Charged Off                                            80.65
Current                                                85.93
Default                                                77.50
Does not meet the credit policy. Status:Charged Off    61.37
Does not meet the credit policy. Status:Fully Paid     71.53
Fully Paid                                             83.60
In Grace Period                                        83.04
Late (16-30 days)                                      83.08
Late (31-120 days)                                     81.24
Name: mths_since_last_record, dtype: float64

 mths_since_recent_bc_dlq
loan_status
Charged Off                                             75.07
Current                                                 78.16
Default                                                 77.50
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              76.59
In Grace Period                                         73.91
Late (16-30 days)                                       72.94
Late (31-120 days)                                      74.72
Name: mths_since_recent_bc_dlq, dtype: float64

 mths_since_last_major_derog
loan_status
Charged Off                                             71.10
Current                                                 75.34
Default                                                 82.50
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              74.35
In Grace Period                                         69.94
Late (16-30 days)                                       69.35
Late (31-120 days)                                      69.49
Name: mths_since_last_major_derog, dtype: float64

 mths_since_recent_revol_delinq
loan_status
Charged Off                                             65.35
Current                                                 68.35
Default                                                 65.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              66.85
In Grace Period                                         62.53
Late (16-30 days)                                       61.92
Late (31-120 days)                                      64.54
Name: mths_since_recent_revol_delinq, dtype: float64

 mths_since_last_delinq
loan_status
Charged Off                                            48.68
Current                                                52.67
Default                                                45.00
Does not meet the credit policy. Status:Charged Off    38.76
Does not meet the credit policy. Status:Fully Paid     45.47
Fully Paid                                             50.89
In Grace Period                                        45.00
Late (16-30 days)                                      44.61
Late (31-120 days)                                     47.36
Name: mths_since_last_delinq, dtype: float64

 next_pymnt_d
loan_status
Charged Off                                            100.0
Current                                                  0.0
Default                                                  0.0
Does not meet the credit policy. Status:Charged Off      0.0
Does not meet the credit policy. Status:Fully Paid       0.0
Fully Paid                                             100.0
In Grace Period                                          0.0
Late (16-30 days)                                        0.0
Late (31-120 days)                                       0.0
Name: next_pymnt_d, dtype: float64

Columns between 20 and 50

In [25]:
cols_20 = summary.loc[(summary["Missing %"] >= 20) & (summary["Missing %"] < 50), "Column"].tolist()
print(cols_20)
print(len(cols_20))

['il_util', 'mths_since_rcnt_il', 'all_util', 'open_acc_6m', 'open_act_il', 'open_rv_24m', 'open_rv_12m', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'max_bal_bc', 'total_bal_il', 'open_il_12m', 'open_il_24m']
14

In [26]:
df[cols_20].describe()

,il_util,mths_since_rcnt_il,all_util,open_acc_6m,open_act_il,open_rv_24m,open_rv_12m,inq_fi,total_cu_tl,inq_last_12m,max_bal_bc,total_bal_il,open_il_12m,open_il_24m
count,1.191818e+06,1.350744e+06,1.394320e+06,1.394538e+06,1.394539e+06,1.394539e+06,1.394539e+06,1.394539e+06,1.394538e+06,1.394538e+06,1.394539e+06,1.394539e+06,1.394539e+06,1.394539e+06
mean,6.914098e+01,2.122236e+01,5.703230e+01,9.344199e-01,2.779407e+00,2.749923e+00,1.290133e+00,1.012867e+00,1.477304e+00,2.036667e+00,5.806393e+03,3.550665e+04,6.764314e-01,1.562752e+00
std,2.374839e+01,2.604919e+01,2.090475e+01,1.140700e+00,3.000784e+00,2.596911e+00,1.506827e+00,1.489456e+00,2.672991e+00,2.383117e+00,5.690561e+03,4.409746e+04,9.256354e-01,1.578672e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.500000e+01,7.000000e+00,4.300000e+01,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.284000e+03,8.695000e+03,0.000000e+00,0.000000e+00
50%,7.200000e+01,1.300000e+01,5.800000e+01,1.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,4.413000e+03,2.312700e+04,0.000000e+00,1.000000e+00
75%,8.600000e+01,2.400000e+01,7.200000e+01,1.000000e+00,3.000000e+00,4.000000e+00,2.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,7.598000e+03,4.609500e+04,1.000000e+00,2.000000e+00
max,1.000000e+03,5.110000e+02,2.390000e+02,1.800000e+01,5.700000e+01,6.000000e+01,2.800000e+01,4.800000e+01,1.110000e+02,6.700000e+01,1.170668e+06,1.837038e+06,2.500000e+01,5.100000e+01

In [27]:
cols_20 = [
    "il_util",
    "mths_since_rcnt_il",
    "all_util",
    "open_acc_6m",
    "open_act_il",
    "open_rv_24m",
    "open_rv_12m",
    "inq_fi",
    "total_cu_tl",
    "inq_last_12m",
    "max_bal_bc",
    "total_bal_il",
    "open_il_12m",
    "open_il_24m"
]

for col in cols_20:
    print("\n", col)
    print(
        df.groupby("loan_status")[col]
          .apply(lambda x: x.isna().mean() * 100)
          .round(2)
    )

 il_util
loan_status
Charged Off                                             60.94
Current                                                 20.32
Default                                                 22.50
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              66.56
In Grace Period                                         21.99
Late (16-30 days)                                       22.12
Late (31-120 days)                                      21.09
Name: il_util, dtype: float64

 mths_since_rcnt_il
loan_status
Charged Off                                             56.69
Current                                                  9.27
Default                                                  7.50
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              62.20
In Grace Period                                         11.91
Late (16-30 days)                                       11.24
Late (31-120 days)                                      10.86
Name: mths_since_rcnt_il, dtype: float64

 all_util
loan_status
Charged Off                                             55.28
Current                                                  6.05
Default                                                  5.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              61.23
In Grace Period                                          9.09
Late (16-30 days)                                        7.91
Late (31-120 days)                                       7.39
Name: all_util, dtype: float64

 open_acc_6m
loan_status
Charged Off                                             55.28
Current                                                  6.03
Default                                                  5.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              61.23
In Grace Period                                          9.08
Late (16-30 days)                                        7.86
Late (31-120 days)                                       7.38
Name: open_acc_6m, dtype: float64

 open_act_il
loan_status
Charged Off                                             55.28
Current                                                  6.03
Default                                                  5.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              61.23
In Grace Period                                          9.08
Late (16-30 days)                                        7.86
Late (31-120 days)                                       7.38
Name: open_act_il, dtype: float64

 open_rv_24m
loan_status
Charged Off                                             55.28
Current                                                  6.03
Default                                                  5.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              61.23
In Grace Period                                          9.08
Late (16-30 days)                                        7.86
Late (31-120 days)                                       7.38
Name: open_rv_24m, dtype: float64

 open_rv_12m
loan_status
Charged Off                                             55.28
Current                                                  6.03
Default                                                  5.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              61.23
In Grace Period                                          9.08
Late (16-30 days)                                        7.86
Late (31-120 days)                                       7.38
Name: open_rv_12m, dtype: float64

 inq_fi
loan_status
Charged Off                                             55.28
Current                                                  6.03
Default                                                  5.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              61.23
In Grace Period                                          9.08
Late (16-30 days)                                        7.86
Late (31-120 days)                                       7.38
Name: inq_fi, dtype: float64

 total_cu_tl
loan_status
Charged Off                                             55.28
Current                                                  6.03
Default                                                  5.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              61.23
In Grace Period                                          9.08
Late (16-30 days)                                        7.86
Late (31-120 days)                                       7.38
Name: total_cu_tl, dtype: float64

 inq_last_12m
loan_status
Charged Off                                             55.28
Current                                                  6.03
Default                                                  5.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              61.23
In Grace Period                                          9.08
Late (16-30 days)                                        7.86
Late (31-120 days)                                       7.38
Name: inq_last_12m, dtype: float64

 max_bal_bc
loan_status
Charged Off                                             55.28
Current                                                  6.03
Default                                                  5.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              61.23
In Grace Period                                          9.08
Late (16-30 days)                                        7.86
Late (31-120 days)                                       7.38
Name: max_bal_bc, dtype: float64

 total_bal_il
loan_status
Charged Off                                             55.28
Current                                                  6.03
Default                                                  5.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              61.23
In Grace Period                                          9.08
Late (16-30 days)                                        7.86
Late (31-120 days)                                       7.38
Name: total_bal_il, dtype: float64

 open_il_12m
loan_status
Charged Off                                             55.28
Current                                                  6.03
Default                                                  5.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              61.23
In Grace Period                                          9.08
Late (16-30 days)                                        7.86
Late (31-120 days)                                       7.38
Name: open_il_12m, dtype: float64

 open_il_24m
loan_status
Charged Off                                             55.28
Current                                                  6.03
Default                                                  5.00
Does not meet the credit policy. Status:Charged Off    100.00
Does not meet the credit policy. Status:Fully Paid     100.00
Fully Paid                                              61.23
In Grace Period                                          9.08
Late (16-30 days)                                        7.86
Late (31-120 days)                                       7.38
Name: open_il_24m, dtype: float64

Columns between 0 and 20

In [28]:
cols_0 = summary.loc[(summary["Missing %"] > 0) & (summary["Missing %"] < 20), "Column"].tolist()
print(len(cols_0))
print(cols_0)

44
['mths_since_recent_inq', 'emp_title', 'num_tl_120dpd_2m', 'emp_length', 'mo_sin_old_il_acct', 'bc_util', 'percent_bc_gt_75', 'bc_open_to_buy', 'mths_since_recent_bc', 'pct_tl_nvr_dlq', 'avg_cur_bal', 'mo_sin_rcnt_rev_tl_op', 'total_rev_hi_lim', 'num_rev_accts', 'tot_cur_bal', 'tot_coll_amt', 'mo_sin_old_rev_tl_op', 'num_il_tl', 'num_bc_tl', 'num_actv_rev_tl', 'num_rev_tl_bal_gt_0', 'num_actv_bc_tl', 'num_accts_ever_120_pd', 'tot_hi_cred_lim', 'total_il_high_credit_limit', 'num_tl_30dpd', 'num_op_rev_tl', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'mo_sin_rcnt_tl', 'num_sats', 'num_bc_sats', 'acc_open_past_24mths', 'mort_acc', 'total_bc_limit', 'total_bal_ex_mort', 'title', 'last_pymnt_d', 'revol_util', 'dti', 'pub_rec_bankruptcies', 'tax_liens', 'chargeoff_within_12_mths', 'collections_12_mths_ex_med']

In [29]:
df[cols_0].dtypes

mths_since_recent_inq         float64
emp_title                      object
num_tl_120dpd_2m              float64
emp_length                     object
mo_sin_old_il_acct            float64
bc_util                       float64
percent_bc_gt_75              float64
bc_open_to_buy                float64
mths_since_recent_bc          float64
pct_tl_nvr_dlq                float64
avg_cur_bal                   float64
mo_sin_rcnt_rev_tl_op         float64
total_rev_hi_lim              float64
num_rev_accts                 float64
tot_cur_bal                   float64
tot_coll_amt                  float64
mo_sin_old_rev_tl_op          float64
num_il_tl                     float64
num_bc_tl                     float64
num_actv_rev_tl               float64
num_rev_tl_bal_gt_0           float64
num_actv_bc_tl                float64
num_accts_ever_120_pd         float64
tot_hi_cred_lim               float64
total_il_high_credit_limit    float64
num_tl_30dpd                  float64
num_op_rev_tl                 float64
num_tl_90g_dpd_24m            float64
num_tl_op_past_12m            float64
mo_sin_rcnt_tl                float64
num_sats                      float64
num_bc_sats                   float64
acc_open_past_24mths          float64
mort_acc                      float64
total_bc_limit                float64
total_bal_ex_mort             float64
title                          object
last_pymnt_d                   object
revol_util                    float64
dti                           float64
pub_rec_bankruptcies          float64
tax_liens                     float64
chargeoff_within_12_mths      float64
collections_12_mths_ex_med    float64
dtype: object

In [30]:
categorical_col_0 = df[cols_0].select_dtypes(include='object').columns.tolist()

print(categorical_col_0)

['emp_title', 'emp_length', 'title', 'last_pymnt_d']

In [31]:
numerical_col_0 = df[cols_0].select_dtypes(include='number').columns.tolist()

print(numerical_col_0)

['mths_since_recent_inq', 'num_tl_120dpd_2m', 'mo_sin_old_il_acct', 'bc_util', 'percent_bc_gt_75', 'bc_open_to_buy', 'mths_since_recent_bc', 'pct_tl_nvr_dlq', 'avg_cur_bal', 'mo_sin_rcnt_rev_tl_op', 'total_rev_hi_lim', 'num_rev_accts', 'tot_cur_bal', 'tot_coll_amt', 'mo_sin_old_rev_tl_op', 'num_il_tl', 'num_bc_tl', 'num_actv_rev_tl', 'num_rev_tl_bal_gt_0', 'num_actv_bc_tl', 'num_accts_ever_120_pd', 'tot_hi_cred_lim', 'total_il_high_credit_limit', 'num_tl_30dpd', 'num_op_rev_tl', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'mo_sin_rcnt_tl', 'num_sats', 'num_bc_sats', 'acc_open_past_24mths', 'mort_acc', 'total_bc_limit', 'total_bal_ex_mort', 'revol_util', 'dti', 'pub_rec_bankruptcies', 'tax_liens', 'chargeoff_within_12_mths', 'collections_12_mths_ex_med']

In [32]:
summary = pd.DataFrame({
        "Column": cols_0,
        "Missing Values": df[cols_0].isnull().sum().values,
        "Missing %": (df[cols_0].isnull().sum().values / len(df) * 100).round(2)
})

summary = summary.sort_values("Missing %", ascending=False)
summary.head(20)

                   Column  Missing Values  Missing %
0   mths_since_recent_inq          295468      13.07
1               emp_title          167002       7.39
2        num_tl_120dpd_2m          153690       6.80
3              emp_length          146940       6.50
4      mo_sin_old_il_acct          139104       6.15
5                 bc_util           76104       3.37
6        percent_bc_gt_75           75412       3.34
7          bc_open_to_buy           74968       3.32
8    mths_since_recent_bc           73445       3.25
9          pct_tl_nvr_dlq           70464       3.12
10            avg_cur_bal           70379       3.11
11  mo_sin_rcnt_rev_tl_op           70310       3.11
12       total_rev_hi_lim           70309       3.11
13          num_rev_accts           70310       3.11
14            tot_cur_bal           70309       3.11
15           tot_coll_amt           70309       3.11
16   mo_sin_old_rev_tl_op           70310       3.11
17              num_il_tl           70309       3.11
18              num_bc_tl           70309       3.11
19        num_actv_rev_tl           70309       3.11

fill emp_title and title with Unkown

In [33]:
df["emp_title"] = df["emp_title"].fillna("Unknown")

In [34]:
df["title"] = df["title"].fillna("Unknown")

Convert last_pymnt_d to datetime

In [35]:
df["last_pymnt_d"] = pd.to_datetime(df["last_pymnt_d"])

C:\Users\Ahmad Ramiz Qeyam\AppData\Local\Temp\ipykernel_16084\168070533.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["last_pymnt_d"] = pd.to_datetime(df["last_pymnt_d"])

Change emp_length to numeric

In [36]:
df["emp_length"].value_counts(dropna=False)

emp_length
10+ years    748005
2 years      203677
< 1 year     189988
3 years      180753
1 year       148403
NaN          146940
5 years      139698
4 years      136605
6 years      102628
7 years       92695
8 years       91914
9 years       79395
Name: count, dtype: int64

In [37]:
df["emp_length"] = df["emp_length"].replace({
    "< 1 year": 0,
    "1 year": 1,
    "2 years": 2,
    "3 years": 3,
    "4 years": 4,
    "5 years": 5,
    "6 years": 6,
    "7 years": 7,
    "8 years": 8,
    "9 years": 9,
    "10+ years": 10
})

C:\Users\Ahmad Ramiz Qeyam\AppData\Local\Temp\ipykernel_16084\3291768626.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["emp_length"] = df["emp_length"].replace({

In [38]:
df["emp_length"].value_counts(dropna=False)

emp_length
10.0    748005
2.0     203677
0.0     189988
3.0     180753
1.0     148403
NaN     146940
5.0     139698
4.0     136605
6.0     102628
7.0      92695
8.0      91914
9.0      79395
Name: count, dtype: int64

Numerical columns

In [39]:
numerical_summary = df[numerical_col_0].describe().T

numerical_summary["Missing"] = df[numerical_col_0].isnull().sum()
numerical_summary["Missing %"] = (
    numerical_summary["Missing"] / len(df) * 100
).round(2)

numerical_summary = numerical_summary[
    ["Missing", "Missing %", "min", "50%", "max"]
]

numerical_summary

                            Missing  Missing %  min        50%        max
mths_since_recent_inq        295468      13.07  0.0       5.00       25.0
num_tl_120dpd_2m             153690       6.80  0.0       0.00        7.0
mo_sin_old_il_acct           139104       6.15  0.0     130.00      999.0
bc_util                       76104       3.37  0.0      60.20      339.6
percent_bc_gt_75              75412       3.34  0.0      37.50      100.0
bc_open_to_buy                74968       3.32  0.0    5442.00   711140.0
mths_since_recent_bc          73445       3.25  0.0      14.00      661.0
pct_tl_nvr_dlq                70464       3.12  0.0     100.00      100.0
avg_cur_bal                   70379       3.11  0.0    7335.00   958084.0
mo_sin_rcnt_rev_tl_op         70310       3.11  0.0       8.00      547.0
total_rev_hi_lim              70309       3.11  0.0   25400.00  9999999.0
num_rev_accts                 70310       3.11  0.0      12.00      151.0
tot_cur_bal                   70309       3.11  0.0   79240.00  9971659.0
tot_coll_amt                  70309       3.11  0.0       0.00  9152545.0
mo_sin_old_rev_tl_op          70310       3.11  1.0     164.00      999.0
num_il_tl                     70309       3.11  0.0       6.00      159.0
num_bc_tl                     70309       3.11  0.0       7.00       86.0
num_actv_rev_tl               70309       3.11  0.0       5.00       72.0
num_rev_tl_bal_gt_0           70309       3.11  0.0       5.00       65.0
num_actv_bc_tl                70309       3.11  0.0       3.00       50.0
num_accts_ever_120_pd         70309       3.11  0.0       0.00       58.0
tot_hi_cred_lim               70309       3.11  0.0  114298.50  9999999.0
total_il_high_credit_limit    70309       3.11  0.0   32696.00  2118996.0
num_tl_30dpd                  70309       3.11  0.0       0.00        4.0
num_op_rev_tl                 70309       3.11  0.0       7.00       91.0
num_tl_90g_dpd_24m            70309       3.11  0.0       0.00       58.0
num_tl_op_past_12m            70309       3.11  0.0       2.00       32.0
mo_sin_rcnt_tl                70309       3.11  0.0       6.00      382.0
num_sats                      58623       2.59  0.0      11.00      101.0
num_bc_sats                   58623       2.59  0.0       4.00       71.0
acc_open_past_24mths          50063       2.21  0.0       4.00       64.0
mort_acc                      50063       2.21  0.0       1.00       94.0
total_bc_limit                50063       2.21  0.0   16300.00  1569000.0
total_bal_ex_mort             50063       2.21  0.0   37864.00  3408095.0
revol_util                     1835       0.08  0.0      50.30      892.3
dti                            1744       0.08 -1.0      17.84      999.0
pub_rec_bankruptcies           1398       0.06  0.0       0.00       12.0
tax_liens                       138       0.01  0.0       0.00       85.0
chargeoff_within_12_mths        178       0.01  0.0       0.00       10.0
collections_12_mths_ex_med      178       0.01  0.0       0.00       20.0

Check all 40 columns against issue_d

In [40]:
df["issue_d"] = pd.to_datetime(df["issue_d"])

C:\Users\Ahmad Ramiz Qeyam\AppData\Local\Temp\ipykernel_16084\174840125.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["issue_d"] = pd.to_datetime(df["issue_d"])

In [41]:
missing_by_year = df.groupby(df["issue_d"].dt.year)[numerical_col_0].apply(lambda x: x.isna().mean() * 100)

missing_by_year

,mths_since_recent_inq,num_tl_120dpd_2m,mo_sin_old_il_acct,bc_util,percent_bc_gt_75,bc_open_to_buy,mths_since_recent_bc,pct_tl_nvr_dlq,avg_cur_bal,mo_sin_rcnt_rev_tl_op,...,acc_open_past_24mths,mort_acc,total_bc_limit,total_bal_ex_mort,revol_util,dti,pub_rec_bankruptcies,tax_liens,chargeoff_within_12_mths,collections_12_mths_ex_med
issue_d,,,,,,,,,,,,,,,,,,,,,
2007.0,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.00000,100.00000,100.00000,100.00000,5.306799,0.000000,96.683250,17.412935,24.046434,24.046434
2008.0,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.00000,100.00000,100.00000,100.00000,0.501463,0.000000,32.553280,0.000000,0.000000,0.000000
2009.0,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.00000,100.00000,100.00000,100.00000,0.302973,0.000000,0.056807,0.000000,0.000000,0.000000
2010.0,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.00000,100.00000,100.00000,100.00000,0.167504,0.000000,0.000000,0.000000,0.000000,0.000000
2011.0,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.00000,100.00000,100.00000,100.00000,0.041435,0.000000,0.000000,0.000000,0.000000,0.000000
2012.0,24.895535,51.981562,54.185171,15.076733,15.026140,15.026140,14.893099,51.981562,51.981562,51.983435,...,14.04426,14.04426,14.04426,14.04426,0.088069,0.000000,0.000000,0.000000,0.000000,0.000000
2013.0,10.816384,0.189891,3.675434,0.790719,0.748439,0.746213,0.652751,0.113490,0.004451,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.057857,0.000000,0.000000,0.000000,0.000000,0.000000
2014.0,9.205998,3.335752,3.043344,1.108098,1.085181,1.037648,0.953193,0.000000,0.002546,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.053049,0.000000,0.000000,0.000000,0.000000,0.000000
2015.0,10.591197,4.566665,2.910032,1.003811,1.006661,0.941118,0.901934,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.038471,0.000475,0.000000,0.000000,0.000000,0.000000
2016.0,10.470135,4.920961,2.694017,1.113012,1.073878,1.066972,1.006890,0.000000,0.000000,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.060773,0.014503,0.000000,0.000000,0.000000,0.000000
2017.0,11.712232,5.016919,2.959112,1.340911,1.298303,1.294922,1.224810,0.000000,0.004058,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.100095,0.115876,0.000000,0.000000,0.000000,0.000000
2018.0,12.378797,2.504634,3.717375,1.373672,1.331874,1.330259,1.251509,0.000404,0.008077,0.000000,...,0.00000,0.00000,0.00000,0.00000,0.119538,0.228575,0.000000,0.000000,0.000000,0.000000

In [42]:
df["issue_d"].dt.year.value_counts().sort_index()

issue_d
2007.0       603
2008.0      2393
2009.0      5281
2010.0     12537
2011.0     21721
2012.0     53367
2013.0    134814
2014.0    235629
2015.0    421095
2016.0    434407
2017.0    443579
2018.0    495242
Name: count, dtype: int64

from 2007-2011 are about 1.9% of dataset so i removed them

In [43]:
df = df[df["issue_d"].dt.year >= 2012].copy()

In [44]:
print(df.shape)
print(df["issue_d"].dt.year.min())

(2218133, 113)
2012

In [45]:
summary = pd.DataFrame({
        "Column": cols_0,
        "Missing Values": df[cols_0].isnull().sum().values,
        "Missing %": (df[cols_0].isnull().sum().values / len(df) * 100).round(2)
})

summary = summary.sort_values("Missing %", ascending=False)
summary.head(30)

                        Column  Missing Values  Missing %
0        mths_since_recent_inq          252900      11.40
3                   emp_length          145795       6.57
2             num_tl_120dpd_2m          111122       5.01
4           mo_sin_old_il_acct           96536       4.35
5                      bc_util           33536       1.51
6             percent_bc_gt_75           32844       1.48
7               bc_open_to_buy           32400       1.46
8         mths_since_recent_bc           30877       1.39
9               pct_tl_nvr_dlq           27896       1.26
10                 avg_cur_bal           27811       1.25
11       mo_sin_rcnt_rev_tl_op           27742       1.25
12            total_rev_hi_lim           27741       1.25
28          num_tl_op_past_12m           27741       1.25
13               num_rev_accts           27742       1.25
14                 tot_cur_bal           27741       1.25
15                tot_coll_amt           27741       1.25
16        mo_sin_old_rev_tl_op           27742       1.25
17                   num_il_tl           27741       1.25
18                   num_bc_tl           27741       1.25
19             num_actv_rev_tl           27741       1.25
20         num_rev_tl_bal_gt_0           27741       1.25
21              num_actv_bc_tl           27741       1.25
22       num_accts_ever_120_pd           27741       1.25
23             tot_hi_cred_lim           27741       1.25
24  total_il_high_credit_limit           27741       1.25
25                num_tl_30dpd           27741       1.25
26               num_op_rev_tl           27741       1.25
27          num_tl_90g_dpd_24m           27741       1.25
29              mo_sin_rcnt_tl           27741       1.25
30                    num_sats           16055       0.72

Investigate these columns because it shows different types

In [46]:
for col in ["bc_util", "avg_cur_bal", "num_rev_accts", "num_tl_120dpd_2m", "mort_acc"]:
    print("\n", col)
    print(df.groupby("loan_status")[col].apply(lambda x: x.isna().mean() * 100))

 bc_util
loan_status
Charged Off           1.645942
Current               1.242148
Default               5.000000
Fully Paid            1.707117
In Grace Period       1.410621
Late (16-30 days)     1.356634
Late (31-120 days)    1.490660
Name: bc_util, dtype: float64

 avg_cur_bal
loan_status
Charged Off           1.770709
Current               0.005351
Default               0.000000
Fully Paid            2.216308
In Grace Period       0.000000
Late (16-30 days)     0.000000
Late (31-120 days)    0.004658
Name: avg_cur_bal, dtype: float64

 num_rev_accts
loan_status
Charged Off           1.768047
Current               0.000000
Default               0.000000
Fully Paid            2.214965
In Grace Period       0.000000
Late (16-30 days)     0.000000
Late (31-120 days)    0.000000
Name: num_rev_accts, dtype: float64

 num_tl_120dpd_2m
loan_status
Charged Off           6.942854
Current               3.578093
Default               5.000000
Fully Paid            5.693555
In Grace Period       5.310574
Late (16-30 days)     6.254311
Late (31-120 days)    6.325989
Name: num_tl_120dpd_2m, dtype: float64

 mort_acc
loan_status
Charged Off           0.462553
Current               0.000000
Default               0.000000
Fully Paid            0.602224
In Grace Period       0.000000
Late (16-30 days)     0.000000
Late (31-120 days)    0.000000
Name: mort_acc, dtype: float64

Calculate the medians

In [47]:
median_cols = [col for col in numerical_col_0
               if col not in[
                "mths_since_recent_inq",
                "mo_sin_old_il_acct",
                "mths_since_recent_bc",
                "mo_sin_rcnt_rev_tl_op",
                "mo_sin_old_rev_tl_op",
                "mo_sin_rcnt_tl"
               ]
]

print(df[median_cols].median())

num_tl_120dpd_2m                   0.00
bc_util                           60.20
percent_bc_gt_75                  37.50
bc_open_to_buy                  5442.00
pct_tl_nvr_dlq                   100.00
avg_cur_bal                     7335.00
total_rev_hi_lim               25400.00
num_rev_accts                     12.00
tot_cur_bal                    79240.00
tot_coll_amt                       0.00
num_il_tl                          6.00
num_bc_tl                          7.00
num_actv_rev_tl                    5.00
num_rev_tl_bal_gt_0                5.00
num_actv_bc_tl                     3.00
num_accts_ever_120_pd              0.00
tot_hi_cred_lim               114298.50
total_il_high_credit_limit     32696.00
num_tl_30dpd                       0.00
num_op_rev_tl                      7.00
num_tl_90g_dpd_24m                 0.00
num_tl_op_past_12m                 2.00
num_sats                          11.00
num_bc_sats                        4.00
acc_open_past_24mths               4.00
mort_acc                           1.00
total_bc_limit                 16300.00
total_bal_ex_mort              37864.00
revol_util                        50.30
dti                               17.93
pub_rec_bankruptcies               0.00
tax_liens                          0.00
chargeoff_within_12_mths           0.00
collections_12_mths_ex_med         0.00
dtype: float64

In [48]:
for col in median_cols:
    df[col] = df[col].fillna(df[col].median())

In [49]:
df[median_cols].isnull().sum()

num_tl_120dpd_2m              0
bc_util                       0
percent_bc_gt_75              0
bc_open_to_buy                0
pct_tl_nvr_dlq                0
avg_cur_bal                   0
total_rev_hi_lim              0
num_rev_accts                 0
tot_cur_bal                   0
tot_coll_amt                  0
num_il_tl                     0
num_bc_tl                     0
num_actv_rev_tl               0
num_rev_tl_bal_gt_0           0
num_actv_bc_tl                0
num_accts_ever_120_pd         0
tot_hi_cred_lim               0
total_il_high_credit_limit    0
num_tl_30dpd                  0
num_op_rev_tl                 0
num_tl_90g_dpd_24m            0
num_tl_op_past_12m            0
num_sats                      0
num_bc_sats                   0
acc_open_past_24mths          0
mort_acc                      0
total_bc_limit                0
total_bal_ex_mort             0
revol_util                    0
dti                           0
pub_rec_bankruptcies          0
tax_liens                     0
chargeoff_within_12_mths      0
collections_12_mths_ex_med    0
dtype: int64

Inspect the 6 special "month since" columns

In [50]:
special_cols = [
    "mths_since_recent_inq",
    "mo_sin_old_il_acct",
    "mths_since_recent_bc",
    "mo_sin_rcnt_rev_tl_op",
    "mo_sin_old_rev_tl_op",
    "mo_sin_rcnt_tl"
]

df[special_cols].describe()

,mths_since_recent_inq,mo_sin_old_il_acct,mths_since_recent_bc,mo_sin_rcnt_rev_tl_op,mo_sin_old_rev_tl_op,mo_sin_rcnt_tl
count,1.965233e+06,2.121597e+06,2.187256e+06,2.190391e+06,2.190391e+06,2.190392e+06
mean,7.024194e+00,1.257378e+02,2.484485e+01,1.402409e+01,1.814916e+02,8.297469e+00
std,5.965411e+00,5.338218e+01,3.231925e+01,1.753308e+01,9.711845e+01,9.208557e+00
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00
25%,2.000000e+00,9.600000e+01,6.000000e+00,4.000000e+00,1.160000e+02,3.000000e+00
50%,5.000000e+00,1.300000e+02,1.400000e+01,8.000000e+00,1.640000e+02,6.000000e+00
75%,1.100000e+01,1.540000e+02,3.000000e+01,1.700000e+01,2.320000e+02,1.100000e+01
max,2.500000e+01,9.990000e+02,6.610000e+02,5.470000e+02,9.990000e+02,3.820000e+02

In [51]:
df[special_cols].isnull().sum()

mths_since_recent_inq    252900
mo_sin_old_il_acct        96536
mths_since_recent_bc      30877
mo_sin_rcnt_rev_tl_op     27742
mo_sin_old_rev_tl_op      27742
mo_sin_rcnt_tl            27741
dtype: int64

Investigate 20 columns with 20-90% missingness

In [52]:
high_missing = df.columns[
    (df.isnull().mean() * 100 >= 20)
].tolist()

print(len(high_missing))
print(high_missing)

20
['mths_since_last_delinq', 'mths_since_last_record', 'next_pymnt_d', 'mths_since_last_major_derog', 'open_acc_6m', 'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util', 'inq_fi', 'total_cu_tl', 'inq_last_12m', 'mths_since_recent_bc_dlq', 'mths_since_recent_revol_delinq']

In [53]:
summary = pd.DataFrame({
    "Column": high_missing,
    "Missing Value": df[high_missing].isnull().sum().values,
    "Missing %": (df[high_missing].isnull().mean().values * 100).round(2)
})

summary.sort_values("Missing %", ascending=False)

                            Column  Missing Value  Missing %
1           mths_since_last_record        1862628      83.97
18        mths_since_recent_bc_dlq        1698432      76.57
3      mths_since_last_major_derog        1637358      73.82
19  mths_since_recent_revol_delinq        1477774      66.62
2                     next_pymnt_d        1305524      58.86
0           mths_since_last_delinq        1131576      51.01
10                         il_util        1026315      46.27
8               mths_since_rcnt_il         867389      39.10
14                        all_util         823813      37.14
7                      open_il_24m         823594      37.13
4                      open_acc_6m         823595      37.13
5                      open_act_il         823594      37.13
11                     open_rv_12m         823594      37.13
9                     total_bal_il         823594      37.13
6                      open_il_12m         823594      37.13
12                     open_rv_24m         823594      37.13
15                          inq_fi         823594      37.13
13                      max_bal_bc         823594      37.13
17                    inq_last_12m         823595      37.13
16                     total_cu_tl         823595      37.13

for 6 high missing columns, create missing flags

In [54]:
high_missing_flag_cols = [
    "mths_since_last_delinq",
    "mths_since_last_record",
    "next_pymnt_d",
    "mths_since_last_major_derog",
    "mths_since_recent_bc_dlq",
    "mths_since_recent_revol_delinq"
]

for col in high_missing_flag_cols:
    df[col + "_missing"] = df[col].isna().astype(int)

In [55]:
df = df.drop(columns=high_missing_flag_cols)

Drop 14 columns that structurally high missing values

In [56]:
drop_20_50 = [
    "il_util",
    "mths_since_rcnt_il",
    "all_util",
    "open_il_24m",
    "open_acc_6m",
    "open_act_il",
    "open_rv_12m",
    "total_bal_il",
    "open_il_12m",
    "open_rv_24m",
    "inq_fi",
    "max_bal_bc",
    "inq_last_12m",
    "total_cu_tl"
]

df = df.drop(columns=drop_20_50)

In [57]:
df.shape

(2218133, 99)

In [58]:
remain_missing = df.isnull().sum()
remain_missing = remain_missing[remain_missing > 0].sort_values(ascending=False)

print(remain_missing)

mths_since_recent_inq    252900
emp_length               145795
mo_sin_old_il_acct        96536
mths_since_recent_bc      30877
mo_sin_old_rev_tl_op      27742
mo_sin_rcnt_rev_tl_op     27742
mo_sin_rcnt_tl            27741
last_pymnt_d               2344
last_credit_pull_d           68
inq_last_6mths                1
zip_code                      1
dtype: int64

In [59]:
print(df[[col + "_missing" for col in high_missing_flag_cols]].sum())

mths_since_last_delinq_missing            1131576
mths_since_last_record_missing            1862628
next_pymnt_d_missing                      1305524
mths_since_last_major_derog_missing       1637358
mths_since_recent_bc_dlq_missing          1698432
mths_since_recent_revol_delinq_missing    1477774
dtype: int64

Handle 6 "months since" columns

In [60]:
for col in special_cols:
    print("\n", col)
    print(df.groupby(df["issue_d"].dt.year)[col].apply(lambda x: x.isna().mean() * 100))

 mths_since_recent_inq
issue_d
2012    24.895535
2013    10.816384
2014     9.205998
2015    10.591197
2016    10.470135
2017    11.712232
2018    12.378797
Name: mths_since_recent_inq, dtype: float64

 mo_sin_old_il_acct
issue_d
2012    54.185171
2013     3.675434
2014     3.043344
2015     2.910032
2016     2.694017
2017     2.959112
2018     3.717375
Name: mo_sin_old_il_acct, dtype: float64

 mths_since_recent_bc
issue_d
2012    14.893099
2013     0.652751
2014     0.953193
2015     0.901934
2016     1.006890
2017     1.224810
2018     1.251509
Name: mths_since_recent_bc, dtype: float64

 mo_sin_rcnt_rev_tl_op
issue_d
2012    51.983435
2013     0.000000
2014     0.000000
2015     0.000000
2016     0.000000
2017     0.000000
2018     0.000000
Name: mo_sin_rcnt_rev_tl_op, dtype: float64

 mo_sin_old_rev_tl_op
issue_d
2012    51.983435
2013     0.000000
2014     0.000000
2015     0.000000
2016     0.000000
2017     0.000000
2018     0.000000
Name: mo_sin_old_rev_tl_op, dtype: float64

 mo_sin_rcnt_tl
issue_d
2012    51.981562
2013     0.000000
2014     0.000000
2015     0.000000
2016     0.000000
2017     0.000000
2018     0.000000
Name: mo_sin_rcnt_tl, dtype: float64

Create a missing indicator

In [61]:
for col in special_cols:
    df[col + "_missing"] = df[col].isna().astype(int)

then fill with their median

In [62]:
for col in special_cols:
    df[col] = df[col].fillna(df[col].median())

Handle emp_length

In [63]:
df["emp_length_missing"] = df["emp_length"].isna().astype(int)

df["emp_length"] = df["emp_length"].fillna(df["emp_length"].median())

inq_last_6mths has 1 missing values and fill with its median

In [64]:
df["inq_last_6mths"] = df["inq_last_6mths"].fillna(df["inq_last_6mths"].median())

zip_cod has 1 missing value

In [65]:
df["zip_code"] = df["zip_code"].fillna("Unknown")

In [66]:
remain_missing = df.isnull().sum()

remain_missing = remain_missing[remain_missing > 0].sort_values(ascending=False)

print(remain_missing)

last_pymnt_d          2344
last_credit_pull_d      68
dtype: int64

Create missing flags for these 2 columns

In [67]:
date_cols = ["last_pymnt_d", "last_credit_pull_d"]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], format="%b-%Y")

for col in date_cols:
    df[col + "_missing"] = df[col].isna().astype(int)

In [68]:
for col in date_cols:
    print(col, df[col].median())

last_pymnt_d 2018-09-01 00:00:00
last_credit_pull_d 2019-03-01 00:00:00

fill with median

In [69]:
for col in date_cols:
    df[col] = df[col].fillna(df[col].median())

In [70]:
print(df[date_cols].isnull().sum())

last_pymnt_d          0
last_credit_pull_d    0
dtype: int64

In [71]:
remain_missing = df.isnull().sum()
remain_missing = remain_missing[remain_missing > 0]
print(remain_missing)

Series([], dtype: int64)

In [72]:
df.shape

(2218133, 108)

Find suspicious values

In [74]:
cols_999 = []
for col in df.select_dtypes(include="number").columns:
    if (df[col] == 999).any():
        cols_999.append(col)

print(cols_999)

['dti', 'revol_bal', 'total_rec_int', 'collection_recovery_fee', 'last_pymnt_amnt', 'tot_coll_amt', 'tot_cur_bal', 'avg_cur_bal', 'bc_open_to_buy', 'delinq_amnt', 'mo_sin_old_il_acct', 'mo_sin_old_rev_tl_op', 'total_bal_ex_mort', 'total_il_high_credit_limit']

In [75]:
cols_99999 = []
for col in df.select_dtypes(include="number").columns:
    if(df[col] == 9999999).any():
        cols_99999.append(col)

print(cols_99999)

['total_rev_hi_lim', 'tot_hi_cred_lim']

check how many 999s each columns has

In [76]:
for col in cols_999: 
    count = (df[col] == 999).sum()
    percent = (count / len(df)) * 100
    print(f"{col}: {count} ({percent:.2f}%)")

dti: 135 (0.01%)
revol_bal: 65 (0.00%)
total_rec_int: 8 (0.00%)
collection_recovery_fee: 1 (0.00%)
last_pymnt_amnt: 3 (0.00%)
tot_coll_amt: 69 (0.00%)
tot_cur_bal: 10 (0.00%)
avg_cur_bal: 164 (0.01%)
bc_open_to_buy: 232 (0.01%)
delinq_amnt: 1 (0.00%)
mo_sin_old_il_acct: 2 (0.00%)
mo_sin_old_rev_tl_op: 1 (0.00%)
total_bal_ex_mort: 17 (0.00%)
total_il_high_credit_limit: 2 (0.00%)

In [77]:
suspicious_cols = ["dti", "mo_sin_old_il_acct", "mo_sin_old_rev_tl_op"]

for col in suspicious_cols:
    print("\n", col)
    print(df.loc[df[col] == 999, ["loan_status", "issue_d", col]].head(10))

 dti
               loan_status    issue_d    dti
8721            Fully Paid 2015-12-01  999.0
427740             Current 2018-03-01  999.0
429273             Current 2018-03-01  999.0
448397             Current 2018-03-01  999.0
452427          Fully Paid 2018-03-01  999.0
458148             Current 2018-03-01  999.0
462542             Current 2018-02-01  999.0
462653  Late (31-120 days) 2018-02-01  999.0
465657             Current 2018-02-01  999.0
466550             Current 2018-02-01  999.0

 mo_sin_old_il_acct
       loan_status    issue_d  mo_sin_old_il_acct
624681     Current 2017-07-01               999.0
625148  Fully Paid 2017-07-01               999.0

 mo_sin_old_rev_tl_op
       loan_status    issue_d  mo_sin_old_rev_tl_op
920381     Current 2017-05-01                 999.0

Create flag

In [78]:
for col in suspicious_cols:
    df[col + "_999"] = (df[col] == 999).astype(int)

Convert 999 to missing

In [79]:
for col in suspicious_cols:
    df[col] = df[col].replace(999, np.nan)

fill those new NaNs with median

In [80]:
for col in suspicious_cols:
    df[col] = df[col].fillna(df[col].median())

In [81]:
for col in suspicious_cols:
    print(col, (df[col] == 999).sum(), df[col].isnull().sum())

dti 0 0
mo_sin_old_il_acct 0 0
mo_sin_old_rev_tl_op 0 0

Check how many 9999999s each has

In [82]:
for col in cols_99999:
    count = (df[col] == 9999999).sum()
    percent = (count / len(df)) * 100
    print(f"{col}: {count} ({percent:.2f}%)")

total_rev_hi_lim: 3 (0.00%)
tot_hi_cred_lim: 14 (0.00%)

In [83]:
for col in cols_99999:
    print("\n", col)
    print(df.loc[df[col] == 9999999, ["id", "issue_d", "loan_status", col]])

 total_rev_hi_lim
               id    issue_d loan_status  total_rev_hi_lim
289384   48324582 2015-06-01  Fully Paid         9999999.0
1187767  28422899 2014-10-01  Fully Paid         9999999.0
1838679   5619692 2013-06-01  Fully Paid         9999999.0

 tot_hi_cred_lim
                id    issue_d  loan_status  tot_hi_cred_lim
82369     62377410 2015-10-01  Charged Off        9999999.0
289384    48324582 2015-06-01   Fully Paid        9999999.0
312569    46417411 2015-04-01   Fully Paid        9999999.0
546877   117192753 2017-09-01      Current        9999999.0
654326    83670840 2016-06-01   Fully Paid        9999999.0
746258    76271514 2016-04-01   Fully Paid        9999999.0
1022792   73926184 2016-03-01   Fully Paid        9999999.0
1078236   70552580 2016-02-01   Fully Paid        9999999.0
1187767   28422899 2014-10-01   Fully Paid        9999999.0
1194988   27040189 2014-09-01   Fully Paid        9999999.0
1404300  142706082 2018-11-01      Current        9999999.0
1838679    5619692 2013-06-01   Fully Paid        9999999.0
2101679  123977559 2017-11-01   Fully Paid        9999999.0
2235281   91554697 2016-10-01  Charged Off        9999999.0

Create flag

In [84]:
for col in cols_99999:
    df[col + "_9999999"] = (df[col] == 9999999).astype(int)

Convert to NaN

In [85]:
for col in cols_99999:
    df[col] = df[col].replace(9999999, np.nan)

fill with median

In [86]:
for col in cols_99999:
    df[col] = df[col].fillna(df[col].median())

In [87]:
for col in cols_99999:
    print(col, (df[col] == 9999999).sum(), df[col].isnull().sum())

total_rev_hi_lim 0 0
tot_hi_cred_lim 0 0

Check to find other suspicious values

In [88]:
for col in ["annual_inc", "tot_coll_amt", "delinq_amnt"]:
    print("\n", col)

    for threshold in [1_000_000, 5_000_000, 10_000_000]:
        count = (df[col] > threshold).sum()
        print(f"> {threshold:,}: {count} rows")

 annual_inc
> 1,000,000: 568 rows
> 5,000,000: 92 rows
> 10,000,000: 3 rows

 tot_coll_amt
> 1,000,000: 3 rows
> 5,000,000: 3 rows
> 10,000,000: 0 rows

 delinq_amnt
> 1,000,000: 0 rows
> 5,000,000: 0 rows
> 10,000,000: 0 rows

In [89]:
for col, threshold in [("annual_inc", 5000000), ("tot_coll_amt", 1000000)]:
    print("\n", col)
    print(df.loc[df[col] > threshold, ["id", "issue_d", "loan_status", "loan_amnt", col]].sort_values(col, ascending=False))

 annual_inc
                id    issue_d loan_status  loan_amnt   annual_inc
601128   113245115 2017-08-01     Current    30000.0  110000000.0
1673140  101074293 2017-03-01     Current    10000.0   61000000.0
539807   118198788 2017-09-01  Fully Paid     5000.0   10999200.0
1597151  131421578 2018-04-01     Current    16000.0    9930475.0
1413812  143613674 2018-11-01     Current    14000.0    9757200.0
...            ...        ...         ...        ...          ...
1412859  143529760 2018-11-01     Current    15000.0    5214756.0
1416173  142995240 2018-11-01     Current     1000.0    5200000.0
1358750  145268592 2018-12-01     Current    20000.0    5119032.0
690341    78419419 2016-05-01     Current    15000.0    5100000.0
75685     62105285 2015-11-01  Fully Paid    20000.0    5000010.0

[92 rows x 5 columns]

 tot_coll_amt
                id    issue_d loan_status  loan_amnt  tot_coll_amt
1303439   13306689 2014-04-01  Fully Paid    10800.0     9152545.0
454537   129595284 2018-03-01  Fully Paid    32000.0     6214661.0
468067   129130677 2018-02-01  Fully Paid     3600.0     5252395.0

Apply capping

In [90]:
cap_values = {
    "annual_inc": df["annual_inc"].quantile(0.999),
    "tot_coll_amt": df["tot_coll_amt"].quantile(0.999)
}

for col, cap in cap_values.items():
    df[col] = df[col].clip(upper=cap)

In [91]:
print(df["annual_inc"].max())
print(df["tot_coll_amt"].max())

600000.0
21943.812000002246

In [92]:
df.to_csv(r"data\lendingclub_cleaned_missing.csv", index=False)

In [93]:
print(df.shape)
print(df.isnull().sum().sum())

(2218133, 113)
0

Check negative values

In [94]:
numeric_cols = df.select_dtypes(include="number").columns

negative_counts = (df[numeric_cols] < 0).sum()

negative_counts = negative_counts[negative_counts > 0].sort_values(ascending=False)

print(negative_counts)

total_rec_late_fee    8
dti                   2
dtype: int64

Check the actual rows

In [95]:
for col in ["total_rec_late_fee", "dti"]:
    print("\n", col)
    print(df.loc[df[col] < 0, ["id", "loan_amnt", "loan_status", col]])

 total_rec_late_fee
               id  loan_amnt        loan_status  total_rec_late_fee
26167    66413852     8425.0        Charged Off       -2.000000e-10
156754   59221046    12800.0            Current       -9.500000e-09
302725   46517265    15000.0        Charged Off       -5.100000e-09
376033   40856488     8375.0        Charged Off       -1.800000e-09
684019   81160345     6050.0        Charged Off       -2.000000e-09
1056255  71866636    17200.0  Late (16-30 days)       -3.900000e-09
1239543  20778618    16000.0            Current       -5.000000e-10
1298937  13727587    17100.0            Current       -7.000000e-10

 dti
               id  loan_amnt loan_status  dti
1014615  74636850    15000.0  Fully Paid -1.0
1681348  99827944    17000.0  Fully Paid -1.0

Set total_rec_late_fee to 0 because they are tiny numerical precision errors

In [96]:
df.loc[df["total_rec_late_fee"] < 0, "total_rec_late_fee"] = 0

for dti, create flag then use median approach

In [97]:
df["dti_invalid"] = (df["dti"] == -1).astype(int)

df["dti"] = df["dti"].replace(-1, np.nan)
df["dti"] = df["dti"].fillna(df["dti"].median())

check for impossible ranges

In [98]:
percentage_cols = [
    col for col in df.select_dtypes(include="number").columns
    if any(word in col.lower() for word in ["rate", "util", "pct", "percent"])
]

print(percentage_cols)

['int_rate', 'revol_util', 'bc_util', 'pct_tl_nvr_dlq', 'percent_bc_gt_75']

check values above 100

In [99]:
for col in percentage_cols:
    count = (df[col] > 100).sum()
    if count > 0:
        print(f"{col}: {count} values > 100")

revol_util: 7316 values > 100
bc_util: 30906 values > 100

In [101]:
for col in ["revol_util", "bc_util"]:
    print("\n", col)
    print(df.loc[df[col] > 100, ["id", "loan_amnt", "revol_bal", "total_rev_hi_lim", "bc_open_to_buy", "total_bc_limit", col]].sort_values(col, ascending=False).head(10))

 revol_util
                id  loan_amnt  revol_bal  total_rev_hi_lim  bc_open_to_buy  \
1292903   14539247     3500.0     2677.0             300.0          5442.0
1254597   19076217    16500.0     2566.0             700.0           134.0
205263    55038895    35000.0    17770.0            9200.0          4400.0
451909   129694895    20000.0    14325.0            7500.0             0.0
414612    37610886    28000.0   266444.0          305000.0             0.0
1371658  145042144    30000.0    33029.0           19800.0             0.0
108244    61982193    12000.0    14262.0            7800.0             0.0
1182078   28863702    16000.0     5408.0            3000.0             0.0
1206322   25386211    15000.0     7107.0            4000.0             0.0
487966   127340922    22000.0    22770.0           13000.0          6500.0

         total_bc_limit  revol_util
1292903             0.0       892.3
1254597           500.0       366.6
205263           8800.0       193.0
451909           7500.0       191.0
414612           5000.0       184.6
1371658         19800.0       183.8
108244           7800.0       182.8
1182078          3000.0       180.3
1206322          3000.0       177.7
487966          13000.0       175.0

 bc_util
                id  loan_amnt  revol_bal  total_rev_hi_lim  bc_open_to_buy  \
1771802    8886482    10000.0     3114.0            9600.0             0.0
399811    38464931    15000.0    10311.0           10700.0             0.0
1204262   25157734    10000.0     3747.0            6900.0             0.0
1745778   96281142     5500.0     3787.0            5200.0             0.0
350601    42894253    12000.0     2226.0            1900.0             0.0
78047     63702760    12000.0     2243.0            1900.0             0.0
629889   112716885     5000.0    27403.0           28200.0             0.0
405484    38588018     6000.0    13167.0           11500.0             0.0
1206322   25386211    15000.0     7107.0            4000.0             0.0
205263    55038895    35000.0    17770.0            9200.0          4400.0

         total_bc_limit  bc_util
1771802           700.0    339.6
399811            800.0    318.2
1204262           500.0    255.2
1745778          1500.0    252.3
350601            600.0    243.8
78047             600.0    235.3
629889           1500.0    215.7
405484           3000.0    204.6
1206322          3000.0    202.9
205263           8800.0    202.0

Check other ratio/range variables

In [102]:
for col in ["dti", "int_rate"]:
    print("\n", col)
    print("min:", df[col].min())
    print("max:", df[col].max())
    print("p99:", df[col].quantile(0.99))
    print("p99.9:", df[col].quantile(0.999))

 dti
min: 0.0
max: 995.6
p99: 42.88680000000168
p99.9: 104.54868000000249

 int_rate
min: 5.31
max: 30.99
p99: 26.77
p99.9: 30.89

investigate dti values

In [103]:
print(df.loc[df["dti"] > 100, ["id", "issue_d", "loan_status", "loan_amnt", "annual_inc", "dti"]].sort_values("dti", ascending=False).head(20))

                id    issue_d  loan_status  loan_amnt  annual_inc     dti
869994   136323805 2018-07-01      Current    20000.0      1100.0  995.60
529772   119381769 2017-09-01      Current    40000.0      1750.0  995.17
1411429  143151043 2018-11-01      Current    12000.0      1500.0  994.40
625865   113128408 2017-07-01   Fully Paid    15000.0      1000.0  991.57
582098   116865279 2017-08-01      Current    19000.0       500.0  973.17
483927   127883060 2018-02-01      Current     9600.0      2300.0  962.83
1551462  132651508 2018-05-01      Current    35000.0      1000.0  942.17
2054690  125275929 2017-12-01      Current    16000.0       500.0  941.46
1606327  130495139 2018-04-01      Current    27475.0      3500.0  917.87
486981   128202046 2018-02-01      Current     5975.0      1050.0  893.10
1687964   99521628 2017-03-01  Charged Off     6000.0      1000.0  886.77
498673   126731138 2018-01-01      Current     7000.0      1000.0  883.61
579633   116918461 2017-08-01   Fully Paid    16000.0      1061.0  879.55
1373185  144771777 2018-12-01      Current    40000.0      3000.0  855.20
802449   138816399 2018-08-01      Current    12000.0      1500.0  851.20
2096866  121814862 2017-11-01      Current    15000.0      2500.0  847.22
1660696  102652591 2017-03-01      Current    34275.0      1500.0  844.80
2127818  119277883 2017-10-01  Charged Off    18000.0      2000.0  831.97
710457    78119033 2016-05-01   Fully Paid    35000.0      3000.0  822.00
943160   107621733 2017-05-01      Current    11000.0      1000.0  819.96

In [104]:
print("dti > 100:", (df["dti"] > 100).sum())
print("dti > 500:", (df["dti"] > 500).sum())
print("dti > 900:", (df["dti"] > 900).sum())

dti > 100: 2426
dti > 500: 129
dti > 900: 9

Create flag

In [105]:
df["dti_invalid"] = (df["dti"] > 100).astype(int)

In [106]:
df.loc[df["dti"] > 100, "dti"] = np.nan

In [107]:
df["dti"] = df["dti"].fillna(df["dti"].median())

In [108]:
print("Invalid DIT:", df["dti_invalid"].sum())
print("Remaining > 100:", (df["dti"] > 100).sum())
print("Missing:", df["dti"].isnull().sum())

Invalid DIT: 2426
Remaining > 100: 0
Missing: 0

Sepcial placeholder values

In [109]:
placeholder_values = [-1, -999, 999, 999999, 9999999]

for value in placeholder_values:
    print(f"\nValue: {value}")

    counts = (df.select_dtypes(include="number") == value).sum()
    counts = counts[counts > 0].sort_values(ascending=False)
    print(counts)

Value: -1
Series([], dtype: int64)

Value: -999
Series([], dtype: int64)

Value: 999
bc_open_to_buy                232
avg_cur_bal                   164
tot_coll_amt                   69
revol_bal                      65
total_bal_ex_mort              17
tot_cur_bal                    10
total_rec_int                   8
last_pymnt_amnt                 3
total_il_high_credit_limit      2
collection_recovery_fee         1
delinq_amnt                     1
dtype: int64

Value: 999999
Series([], dtype: int64)

Value: 9999999
Series([], dtype: int64)

invetigate those rows

In [111]:
placeholder_999_cols = [
    "bc_open_to_buy",
    "avg_cur_bal",
    "tot_coll_amt",
    "revol_bal",
    "total_bal_ex_mort",
    "tot_cur_bal",
    "total_rec_int",
    "last_pymnt_amnt",
    "total_il_high_credit_limit",
    "collection_recovery_fee",
    "delinq_amnt"
]

for col in placeholder_999_cols:
    print(f"\n{col}")
    print(df.loc[df[col] == 999, ["id", "issue_d", "loan_status", "loan_amnt", col]])

bc_open_to_buy
               id    issue_d  loan_status  loan_amnt  bc_open_to_buy
731      68386577 2015-12-01   Fully Paid     5000.0           999.0
7211     68072121 2015-12-01   Fully Paid     7000.0           999.0
17940    67407047 2015-12-01   Fully Paid    20000.0           999.0
25571    66634414 2015-12-01  Charged Off    15000.0           999.0
37702    65896575 2015-12-01   Fully Paid     8000.0           999.0
...           ...        ...          ...        ...             ...
2220080  91654346 2016-11-01      Current    20000.0           999.0
2237404  91368709 2016-10-01   Fully Paid     3500.0           999.0
2237931  91548013 2016-10-01      Current    10000.0           999.0
2245622  90709146 2016-10-01   Fully Paid     3500.0           999.0
2248830  90441213 2016-10-01      Current    35000.0           999.0

[232 rows x 5 columns]

avg_cur_bal
               id    issue_d  loan_status  loan_amnt  avg_cur_bal
9865     67988691 2015-12-01   Fully Paid     5000.0        999.0
18104    67406769 2015-12-01  Charged Off     6400.0        999.0
32998    66440706 2015-12-01   Fully Paid     4775.0        999.0
44247    65747193 2015-11-01   Fully Paid    15000.0        999.0
52293    65802947 2015-11-01   Fully Paid     5000.0        999.0
...           ...        ...          ...        ...          ...
2158634  95022253 2016-12-01   Fully Paid     9000.0        999.0
2178273  94462152 2016-12-01   Fully Paid    16000.0        999.0
2190570  94376692 2016-12-01   Fully Paid    12000.0        999.0
2202947  93716578 2016-11-01      Current    11200.0        999.0
2241723  91495268 2016-10-01   Fully Paid     4000.0        999.0

[164 rows x 5 columns]

tot_coll_amt
                id    issue_d  loan_status  loan_amnt  tot_coll_amt
28541     65926393 2015-12-01   Fully Paid    20000.0         999.0
39971     65736315 2015-12-01   Fully Paid     8050.0         999.0
46830     65713367 2015-11-01   Fully Paid    10000.0         999.0
52382     65672898 2015-11-01   Fully Paid    10000.0         999.0
63352     65098797 2015-11-01  Charged Off    23100.0         999.0
...            ...        ...          ...        ...           ...
2125980  121002023 2017-10-01      Current     8000.0         999.0
2144617  120640288 2017-10-01      Current     7000.0         999.0
2160470   95159929 2016-12-01      Current    20000.0         999.0
2199829   93971880 2016-11-01      Current    20000.0         999.0
2239863   91436275 2016-10-01   Fully Paid    16000.0         999.0

[69 rows x 5 columns]

revol_bal
                id    issue_d  loan_status  loan_amnt  revol_bal
55141     65190239 2015-11-01   Fully Paid     8000.0      999.0
69444     64361382 2015-11-01   Fully Paid     6225.0      999.0
116708    61391493 2015-10-01   Fully Paid     2000.0      999.0
178724    57672548 2015-08-01  Charged Off     5000.0      999.0
181123    57206571 2015-08-01   Fully Paid     6200.0      999.0
...            ...        ...          ...        ...        ...
2037552   84081075 2016-07-01   Fully Paid     7200.0      999.0
2139855  120621341 2017-10-01  Charged Off    10000.0      999.0
2162720   95102997 2016-12-01      Current     8000.0      999.0
2174638   94742876 2016-12-01   Fully Paid     4000.0      999.0
2242837   91643584 2016-10-01   Fully Paid     8000.0      999.0

[65 rows x 5 columns]

total_bal_ex_mort
                id    issue_d  loan_status  loan_amnt  total_bal_ex_mort
181123    57206571 2015-08-01   Fully Paid     6200.0              999.0
241503    53019132 2015-07-01   Fully Paid     2000.0              999.0
523740   126199619 2018-01-01      Current     3000.0              999.0
558044   118232548 2017-09-01   Fully Paid     1500.0              999.0
712971    78219460 2016-04-01      Current    30000.0              999.0
732254    73884229 2016-04-01      Current    20000.0              999.0
934175   109111172 2017-05-01      Current     1500.0              999.0
1154519   32430266 2014-10-01   Fully Paid     5000.0              999.0
1176859   29694502 2014-10-01  Charged Off    25850.0              999.0
1374694  144303555 2018-12-01      Current    35000.0              999.0
1390011  142814871 2018-12-01      Current    12000.0              999.0
1431259  141873251 2018-11-01      Current     9800.0              999.0
1441622  141268597 2018-10-01      Current     1600.0              999.0
1547939  133302934 2018-05-01      Current    10000.0              999.0
1588939  131477587 2018-04-01      Current     1500.0              999.0
1740138   96353539 2017-01-01   Fully Paid    16000.0              999.0
1928762    1241687 2012-04-01   Fully Paid     3000.0              999.0

tot_cur_bal
                id    issue_d loan_status  loan_amnt  tot_cur_bal
523740   126199619 2018-01-01     Current     3000.0        999.0
558044   118232548 2017-09-01  Fully Paid     1500.0        999.0
934175   109111172 2017-05-01     Current     1500.0        999.0
1154519   32430266 2014-10-01  Fully Paid     5000.0        999.0
1374694  144303555 2018-12-01     Current    35000.0        999.0
1390011  142814871 2018-12-01     Current    12000.0        999.0
1431259  141873251 2018-11-01     Current     9800.0        999.0
1441622  141268597 2018-10-01     Current     1600.0        999.0
1588939  131477587 2018-04-01     Current     1500.0        999.0
1740138   96353539 2017-01-01  Fully Paid    16000.0        999.0

total_rec_int
                id    issue_d  loan_status  loan_amnt  total_rec_int
256181    51317689 2015-06-01   Fully Paid     8300.0          999.0
281873    48816286 2015-05-01   Fully Paid    14000.0          999.0
822190   136899855 2018-08-01      Current    31000.0          999.0
859202   136756577 2018-07-01      Current    16000.0          999.0
973703   105154003 2017-04-01   Fully Paid    20500.0          999.0
1236114   20712199 2014-07-01  Charged Off     8000.0          999.0
1411752  143690703 2018-11-01      Current    20650.0          999.0
1712377   97378507 2017-02-01      Current     5000.0          999.0

last_pymnt_amnt
                id    issue_d loan_status  loan_amnt  last_pymnt_amnt
686600    80539826 2016-05-01  Fully Paid     7200.0            999.0
1172041   30235544 2014-10-01  Fully Paid    16000.0            999.0
1475325  141273298 2018-10-01     Current    40000.0            999.0

total_il_high_credit_limit
                id    issue_d loan_status  loan_amnt  \
1413865  142641808 2018-11-01     Current    10000.0
1981549   88165196 2016-08-01  Fully Paid    18000.0

         total_il_high_credit_limit
1413865                       999.0
1981549                       999.0

collection_recovery_fee
               id    issue_d  loan_status  loan_amnt  collection_recovery_fee
1035655  73419877 2016-03-01  Charged Off    24000.0                    999.0

delinq_amnt
               id    issue_d loan_status  loan_amnt  delinq_amnt
1966337  88900869 2016-09-01  Fully Paid     9600.0        999.0

In [126]:
df.to_csv(r"data\lendingclub_cleaned_outliers.csv", index=False)

In [127]:
print(df.shape)
print(df.isnull().sum().sum())

(2218133, 114)
0